### ISSUE TITLE
Allow removal of added AppUUIDs

### ISSUE THREAD

**Issue by edwinfinch** [pebble/pebble-ios-sdk#10]
We @ Lignite have an iOS app which needs to be able to communicate with 17+ UUIDs. Not all at once of course, just whenever a watchface/watchapp is on the screen. So, you’d probably think we could dynamically set the UUID, this is where the fun begins.

I have found that cannot add more than 10 UUIDs without your watch’s firmware crashing because the number of communication channels begins to make it unstable. So, why not just set 1 UUID and change it when another face opens?

Well, a face/app can’t tell the phone from itself that it’s awake because the channel needs to be open in the first place. I also can’t remove a UUID once it has been added. So if the user ends up using a lot of faces/apps in the time where the app is alive, then it will end up crashing the watch because of the “too many communication channels” issue.

We refuse to: 
-Use JS
-Sideload apps
-Use the same UUID

All that needs to be done to PebbleKit is add the ability to set the UUID more dynamically or fix the amount of communication channels. I would even be happy with just being able to delete UUIDs :smile: 

Thanks for all of your work on PebbleKit, though!

**Comment by edwinfinch** [comment]
Damn, I missed the 1 year anniversary of this issue. I'm glad we no longer refuse to use Javascript anymore lol, imagine being stuck with the same issue one year later.

Hope you guys are doing well! Talk next year!

**Comment by drodriguez** [comment]
First, I want to apologize for the lack of response or action in this issue.

Second, I would like to explain that not every issue receives the same priority. This one is one of them. We don’t think this is an use case that many people will have. Most people deal with only 1 associated UUID, so PebbleKit works perfectly fine for them. We don’t need to add and remove UUIDs in the official Pebble app either. You might think that removing UUIDs should be “easy”, but if you stop and think about it, we never designed the system to remove UUIDs, so many pieces might only be prepared for new UUIDs being added, but not removed. We could have invested some time looking for solution, and we might have discussed this issue, but reached the conclusion that there’s little benefit and a lot of drawbacks, including potentially breaking PebbleKit for a lot of people that currently are using it without problem. Maybe we decided that this is an “enhancement” and that we will reconsider if more people find the current setup limiting.

This is probably not the answer you were looking for, and I’m sorry, but sometimes things are more complicated than what it might seen at first.

**Comment by edwinfinch** [comment]
It's all good, I understand. I think it was the silence that made me angry more than anything. It's nicer to hear that your issue will not be resolved so that you can move on instead of waiting for a third party rather than not hearing anything at all. Regardless, we moved on without waiting that long and are doing just fine 😃 . Hope you guys are doing well too! Thanks for the reply!
