### ISSUE TITLE
appMessagesRemoveUpdateHandler() has no effect

### ISSUE THREAD

**Issue by sjmerel** [pebble/pebble-ios-sdk#13]
```
self.msgHandle = pebbleDevice!.watch.appMessagesAddReceiveUpdateHandler()
{                                                                        
    (watch, message) in                                                  
    NSLog("hello")                                         
    return true                                                          
}                                                                        
pebbleDevice!.watch.appMessagesRemoveUpdateHandler(self.msgHandle!)  
```

This Swift code should not result in anything being logged, because we remove the handler right after adding it, right?  But I do see "hello" printed when a message is received; in fact, if I call this snippet 3 times, I see "hello" printed 3 times for every message.  So it seems that the handlers are not being removed.

**Comment by drodriguez** [comment]
I can confirm this is a bug in our code. Sorry for the inconvenience. We will try to fix it in the next release. 

For the moment, my recommendation will be installing the update handlers and workaround our bug:

```
self.receiveMessage: ((PBWatch, [NSNumber:AnyObject]) -> Bool)? = { (watch, message) in
  NSLog("hello")
  return true;
}
self.msgHandler = pebbleDevice!.watch.appMessagesAddReceiveHandler() { (watch, message) in
  if let receiveMessage = self.receiveMessage {
    return receiveMessage(watch, message)
  } else {
    return false
  }
}

self.receiveMessage = nil
pebbleDevice!.watch.appMessagesRemoveUpdateHandler(self.msgHandle!)
```

**Comment by mrcljx** [comment]
Hi @sjmerel,

this bug has been fixed in _3.1.0_ which is available now.

Thanks for reporting it. :+1:
