### ISSUE TITLE
Why platform iOS 7.1 for SDK 3.0?

### ISSUE THREAD

**Issue by mathiasAichinger** [pebble/pebble-ios-sdk#14]
Why do you need 7.1 and not 7.0? It breaks our pod files and we need update all of them to use 7.1.

**Comment by mrcljx** [comment]
PebbleKit 2.x didn't rely much on CoreBluetooth. We are now using CoreBluetooth-APIs including `CBUUID.UUIDString` and `CBErrorConnectionFailed` which have been only added to 7.1.

**Comment by mrcljx** [comment]
Hey @mathiasAichinger - we published a separate pod named `PebbleKit-Static` (same code as `PebbleKit` but as the name suggests it is a static library) which should work with `7.0`.
