### ISSUE TITLE
3.0 is not available via CocoaPods

### ISSUE THREAD

**Issue by pconno** [pebble/pebble-ios-sdk#15]
Hey all,
I was just trying to update to 3.0 so that we could use bitcode in Runkeeper. It looks like you haven't pushed the changes to CocoaPods yet. Can you please do that? https://cocoapods.org/pods/PebbleKit

**Comment by mrcljx** [comment]
Hey @pconno, I don't know why, but CocoaPods is rather picky about version numbers. You have to use `3.0.0`.
