### ISSUE TITLE
`watch.new` property is incompatible with Objective-C++

### ISSUE THREAD

**Issue by sjmerel** [pebble/pebble-ios-sdk#16]
In PBWatch.h, there's a property called "new"; because that is a C++ keyword, this header file can't be included from Objective-C++ code.

As a workaround, I've surrounded that property declaration with "#ifndef __cplusplus", which works fine but needs to be re-added each time I update the framework.  

Maybe rename the property?

**Comment by mrcljx** [comment]
Thanks for the hint. Renaming it directly is rather hard because we want to maintain backward compatibility.

Will check if we can rename it to something non-conflicting, deprecate the old `new` and wrap it with `#ifndef __cplusplus` - thanks for the hint.

**Comment by mrcljx** [comment]
We included the `#ifdef` in `3.1.1`.
