### ISSUE TITLE
PebbleKit-Static references PebbleKit and hence headers don't parse

### ISSUE THREAD

**Issue by motocodeltd** [pebble/pebble-ios-sdk#17]
moving from PebbleKit to PebbleKit-Static fails because the framework itself fails to be parsed.

e.g.

https://github.com/pebble/pebble-ios-sdk/blob/master/PebbleKit-Static.framework/Versions/A/Headers/PebbleKit.h

references things under PebbleKit but the correct reference is PebbleKit-Static. Therefore importing a header file fails.

**Comment by mrcljx** [comment]
Hi @thenewrohirrim - if you imported `PebbleKit-Static` manually you have to create a symlink from `PebbleKit ->`PebbleKit-Static.framework/Headers` to accommodate for this - the specifics of how to do that largely depend on your project setup.

If you install `PebbleKit-Static` through CocoaPods it will take care of this for you.

**Comment by motocodeltd** [comment]
Hi - thanks for the response.

I installed PebbleKit-Static through cocoapods (pod 'PebbleKit-Static') which did not do this for me.

**Comment by mrcljx** [comment]
What does `pod --version` print for you?

**Comment by motocodeltd** [comment]
0.39.0

**Comment by drodriguez** [comment]
PebbleKit 4.0.0 has just been published in dynamic and static versions. We think the static version should now work correctly. Sorry for the delay.

In any case, we recommend using the dynamic version if you can drop support for iOS 7.
