### ISSUE TITLE
App crashed in ExternalAccessory (iOS9)

### ISSUE THREAD

**Issue by HankMisfit** [pebble/pebble-ios-sdk#19]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000015d6d270

-[EAAccessoryManager _notifyObserversThatAccessoryDisconnectedWithUserInfo:]

And we can't update latest SDK since we need to support iOS7.
I know there is a static lib, but it doesn't work. Even can't build through CocoaPods.

**Comment by mrcljx** [comment]
That error sadly comes from Apple's internal framework. I'm looking into fixing the static lib headers.

**Comment by drodriguez** [comment]
PebbleKit 4.0.0 removes the usage of Bluetooth Classic and `ExternalAccessory.framework`, which makes this problem go away.
