### ISSUE TITLE
appMessagesPushUpdate has incorrect signature (__nullableerror instead of __nullable error)

### ISSUE THREAD

**Issue by nivsto** [pebble/pebble-ios-sdk#20]

**Comment by drodriguez** [comment]
@nivsto, sorry for the late reply: this has been fixed in our internal version and will be released soon. For the time being, please edit that file manually in your copy. Sorry for the inconvenience.

**Comment by drodriguez** [comment]
This problem should have been fixed in PebbleKit 4.0.0. Sorry for the delay.
