### ISSUE TITLE
PebbleKit dynamic framework breaks with bitcode enabled

### ISSUE THREAD

**Issue by corvino** [pebble/pebble-ios-sdk#24]
Embedding PebbleKit allows an archive with bitcode to be created, but doesn't allow exporting with app thinning.

During the export dialogue in Xcode, selecting the radio button for thinning produces an error.

When using xcodebuild on the command line, the error related to the thinning step always occurs, entirely breaking export. Using the default (none) and specifying <none> in the export options do not prevent this.

The most likely culprit seems to be the log message: ""Failed to verify bitcode in PebbleKit.framework/PebbleKit:\nerror: Cannot extract bundle..."

See https://github.com/corvino/PebbleBitcode for a sample project replicating the issue and detailed description.

**Comment by drodriguez** [comment]
I haven’t checked yet, but maybe it is related to the extra steps needed to integrate PebbleKit manually. Can you check if the problem still happens after applying the extra steps and stripping the framework from the unwanted architectures? I pasted the new proposed steps in #23 (below “Integrating PebbleKit Manually”)

**Comment by drodriguez** [comment]
@corvino I have gone through all the steps for exporting except the actual submission to the App Store. I haven’t had any problem when following the steps from the `README.md` file.
