### ISSUE TITLE
Update FirmwareMetadataPlatform for Diorite and Emery

### ISSUE THREAD

**Issue by maxbaeumle** [pebble/pebble-ios-sdk#27]
https://github.com/pebble/pebble-ios-sdk/blob/master/PebbleKit.framework/Headers/PBFirmwareMetadata.h#L17

I only have the value of my early access Pebble 2 ♥️

**Comment by drodriguez** [comment]
We are working on releasing the small pieces of compatibility with Pebble 2. In case you need it, the number for Pebble 2 is decimal 14 (as you probably have already found).
