### ISSUE TITLE
lastConnectedWatch in iOS 10.3

### ISSUE THREAD

**Issue by arlomedia** [pebble/pebble-ios-sdk#28]
Are there any known issues with PebbleKit 4.0 on iOS 10.3? My iOS code was last confirmed working on iOS 10.2, but the PebbleCentral's lastConnectedWatch always returns nil now, and updating my iPhone to iOS 10.3 is the only thing I've changed. I have an original Pebble watch running the last-supported firmware version 3.12.3.

The registeredWatches and connectedWatches arrays are also empty. But the Pebble iOS app shows the watch as connected, and the watch settings page shows the phone as connected. Perhaps there was a new permission added in iOS 10.3 to allow watch access?

I wrote more info, including the code I'm using, on the Pebble developer forum: https://forums.pebble.com/t/no-app-connectivity-in-ios-10-3/29513

**Comment by drodriguez** [comment]
I answered in the forums. It should be better to post the problems there, since we look at them (not as often as we will like). There’s also other people that might be able to help.
