### ISSUE TITLE
Any chance of removing CocoaPods?

### ISSUE THREAD

**Issue by gabebear** [pebble/pebble-ios-sdk#3]
CocoaPods breaks the latest beta versions of XCode fairly frequently... I can just fork and remove it if you guys don't want to maintain a version without CocoaPods.

**Comment by sarfata** [comment]
Can you be more specific? What is the problem you are seeing with CocoaPods?

**Comment by mrcljx** [comment]
PebbleKit doesn't require CocoaPods. You can just manually add the `*.framework` files to your project.
