### ISSUE TITLE
Carthage do no seems to work

### ISSUE THREAD

**Issue by yageek** [pebble/pebble-ios-sdk#6]
Impossible to find the framework after launching  `carthage`

**Comment by yageek** [comment]
False positive. After retesting today, all seems to work. Sorry for polluting the tracker.

**Comment by mrcljx** [comment]
You didn't pollute, forgot to mention that I uploaded a fixed `.zip`. Thanks for reporting it.

**Comment by yageek** [comment]
I still have the problem :( Should I reopen it ? I thought the problem was related to Carthage and I opened a ticket there. 

The response given may help here : https://github.com/Carthage/Carthage/issues/866

**Comment by drodriguez** [comment]
I replied in the Carthage issue, but seems that either the symlinks or the Versions folder is what tripped `codesign` and why our pre-build is not valid. We will see how to fix this soon, sorry.

**Comment by mrcljx** [comment]
@yageek We uploaded a proper dynamic framework with `3.1.0` - would be nice if you could verify that it works for you now. Thanks for reporting it. :+1:

**Comment by yageek** [comment]
Seems to work for me. Thanks for the patch.
